config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :subscribers
  devise_for :authors
  resources :authors do
    resources :profiles
  end
  resources :stories
  resources :categories, :only => [:show]
  get "/pages/:page" => "pages#show"
  
  root :to => redirect('/stories')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :author
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_author!, only: [:new, :create, :edit, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @author = @profile.author
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    if current_author.profile
      redirect_to edit_author_profile_path(current_author, current_author.profile)
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.author_id = current_author.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to author_profile_path(current_author, @profile), notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:author_id, :name, :description)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for([current_author, profile], :html => {:class => "form-horizontal contact-form", :role=> "form"}) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-md-12">
      <%= f.text_field(:name, :class => "form-control", :id => "name", :placeholder => "Display Name", required: true) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-12">
      <textarea name="profile[description]" class="form-control" id="desription" placeholder="About You" rows="8" required></textarea>
    </div>
  </div>
  <button type="submit" name="submit" class="btn send-btn">Update</button>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>
<div class="row">
  <div class="col-md-8">
    <%= render 'form', profile: @profile %>
    <br><br>
  </div>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.author_id %></td>
        <td><%= profile.name %></td>
        <td><%= profile.description %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>Edit Profile</h1>
<div class="row">
  <div class="col-md-8">
    <%= render 'form', profile: @profile %>
    <br><br>
  </div>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @profile.author_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @profile.description %>
</p>