config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :subscribers
  devise_for :authors
  resources :authors do
    resources :profiles
  end
  resources :stories
  resources :categories, :only => [:show]
  get "/pages/:page" => "pages#show"
  
  root :to => redirect('/stories')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_social_share.html.erb
<div class="social-share">
  <span class="social-share-title pull-left text-capitalize">
    By <%= story.author.profile.name %> On 
    <%= story.created_at.to_formatted_s(:long) %>
  </span>
  <ul class="text-center pull-right">
    <li>
      <a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" title="Share on Facebook" target="_blank" class="s-facebook">
	<i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a href="http://twitter.com/home?status=<%= request.original_url %>" title="Share on Twitter" target="_blank" class="s-twitter">
	<i class="fa fa-twitter"></i>
      </a>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FootballDopes<%= " | #{@story.title}" if @story %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar main-menu navbar-default">
    <div class="container">
      <div class="menu-content">
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nfl-navbar-collapse-1">
	    <span class="sr-only">Toggle navigation</span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	  </button>
	  <a class="navbar-brand" href="#">
	    <%= image_tag '/images/logo.png' %>
	  </a>
	</div>
	<div class="collapse navbar-collapse" id="nfl-navbar-collapse-1">
	  <ul class="nav navbar-nav text-uppercase">
	    <li><a href="<%= stories_path %>">Home</a></li>
	    <li><a href="<%= stories_path %>">Stories</a></li>
	    <li><a href="<%= authors_path %>">Authors</a></li>
	    <li><a href="/pages/about">About</a></li>
	    <li><a href="/pages/contact">Contact</a></li>
	    <% if author_signed_in? %>
	      <li class="menu-item-has-children">
		<a data-toggle="dropdown" class="dropdown-toggle" href="#">
		  Authors Only
		  <i class="fa fa-angle-down"></i>
		</a>
		<ul class="sub-menu">
		  <li>
		    <%= link_to 'New Story', new_story_path %>
		    <%= link_to 'Edit Profile', new_author_profile_path(current_author) %>
		    <%= link_to 'Log Out', destroy_author_session_path, :method => :delete %>
		  </li>
		</ul>
	      </li>
	    <% end %>
	  </ul>
	  <% if controller_name != 'pages' and controller_name != 'authors' %>
	    <div class="i_con">
	      <a href="https://www.facebook.com/sharer/sharer.php?u=<%= "#{request.original_url}/#{@last_story.slug}" %>" title="Share on Facebook" target="_blank">
		<i class="active fa fa-facebook"></i>
	      </a>
	      <a href="http://twitter.com/home?status=<%= "#{request.original_url}/#{@last_story.slug}" %>" title="Share on Twitter" target="_blank">
		<i class="active fa fa-twitter"></i>
	      </a>
	    </div>
	  <% end %>
	</div>
      </div>
    </div>
  </nav>

  <%= yield %>

  <footer class="footer-widget-section">
    <div class="container">
      <div class="row">
	<div class="col-md-4">
	  <aside class="footer-widget">
	    <div class="about-img">
	      <%= image_tag '/images/footer-logo.png' %>
	    </div>
	    <div class="about-content">
	      Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed voluptua. At vero eos et accusam et justo duo dlores et ea rebum magna text ar koto din.
	    </div>
	    <div class="address">
	      <h4 class="text-uppercase">contact Info</h4>
	      <p> 239/2 NK Street, DC, USA</p>
	      <p> Phone: +123 456 78900</p>
	      <p>theme@kotha.com</p>
	    </div>
	  </aside>
	</div>
	<div class="col-md-4">
	  <aside class="footer-widget">
	    <h3 class="widget-title text-uppercase">Latest Comments</h3>
	    <div id="myCarousel" class="carousel slide" data-ride="carousel">
	      <ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
	      </ol>
	      <div class="carousel-inner" role="listbox">
		<% @last_comments.each_with_index do |comment, index| %>
		  <% if index == 0 %>
		    <div class="item active">
		  <% else %>
		    <div class="item">
		  <% end %>
		    <div class="single-review">
		      <div class="review-text">
			<p><%= comment.body %></p>
		      </div>
		      <div class="author-id">
			<%= image_tag '/images/author.png' %>
			<div class="author-text">
			  <h4><%= comment.name %></h4>
			  <%= link_to comment.commentable.title, comment.commentable, :class => "text-uppercase" %>
			</div>
		      </div>
		    </div>
		  </div>
		<% end %>
		
	      </div>
	    </div>
	  </aside>
	</div>
	<div class="col-md-4">
	  <aside class="footer-widget">
	    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	    <!-- footballdopes -->
	    <ins class="adsbygoogle"
		 style="display:block"
		 data-ad-client="ca-pub-9292388460078962"
		 data-ad-slot="7594585505"
		 data-ad-format="auto"></ins>
	    <script>
	      (adsbygoogle = window.adsbygoogle || []).push({});
	    </script>
	  </aside>
	</div>
      </div>
    </div>
    <div class="footer-copy">
      <div class="container">
	<div class="row">
	  <div class="col-md-12">
	    <div class="text-center">
	      © 2016 
	      <a href="http://twitter.com/footballdopes">@footballdopes</a>
	    </div>
	  </div>
	</div>
      </div>
    </div>
  </footer>
</body>
</html>